// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ProviderRegistry$Type } from "./ProviderRegistry";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ProviderRegistry"]: ProviderRegistry$Type;
    ["contracts/ProviderRegistry.sol:ProviderRegistry"]: ProviderRegistry$Type;
  }

  interface ContractTypesMap {
    ["ProviderRegistry"]: GetContractReturnType<ProviderRegistry$Type["abi"]>;
    ["contracts/ProviderRegistry.sol:ProviderRegistry"]: GetContractReturnType<ProviderRegistry$Type["abi"]>;
  }
}
